name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Linux
        run: |
          sudo apt-get update
          sudo apt-get install libx11-dev

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.14.1

      - name: Check Formatting
        run: zig fmt --ast-check --check .

      - name: Build
        run: zig build --summary all

      - name: Build with X11 and Magellan
        run: zig build -Dx11=true -Dmagellan=true --summary all